# Generated by Django 5.2.5 on 2025-08-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EngineeringSocialApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
